// Generated by CoffeeScript 1.3.1
(function() {
  var Asana, Backbone, addObjects, b64, defaults, isEmpty, querystringify, _ref;

  _ref = require("./utils"), b64 = _ref.b64, defaults = _ref.defaults, querystringify = _ref.querystringify, isEmpty = _ref.isEmpty;

  Backbone = require("backbone");

  addObjects = require("./objects");

  Asana = (function() {

    Asana.name = 'Asana';

    function Asana(opts) {
      this.asana = {
        params: {
          auth: b64("" + opts.key + ":"),
          path: opts.path || "/api/1.0",
          host: opts.host || "app.asana.com",
          scheme: opts.scheme || "https",
          options: opts.options || {}
        },
        Backbone: opts.Backbone || Backbone,
        read: function() {
          return {
            method: "GET",
            expects: 200
          };
        }
      };
      if (this.asana.params.scheme === "https") {
        this.asana.http = require("https");
        this.asana.params.port = opts.port || 443;
      } else {
        this.asana.http = require("http");
        this.asana.params.port = opts.port || 80;
      }
      addObjects(this);
      this.user = new this.User;
      this.user.url = "/users/me";
    }

    Asana.prototype.sync = function(method, model, opts) {
      var error, expects, headers, http_opts, options, params, query, req, success, url;
      if (opts == null) {
        opts = {};
      }
      params = model.asana[method]();
      url = typeof this.url === "function" ? this.url() : this.url;
      expects = params.expects || 200;
      query = params.query;
      error = opts.error || function() {};
      success = opts.success || function() {};
      options = defaults(this.asana.params.options, opts.asana);
      headers = {
        "Accept": "application/json",
        "Authorization": "Basic " + this.asana.params.auth
      };
      http_opts = {
        host: this.asana.params.host,
        port: this.asana.params.port,
        method: params.method || "GET",
        path: "" + this.asana.params.path + url,
        headers: headers,
        scheme: this.asana.params.scheme
      };
      if (!isEmpty(options)) {
        if (http_opts.method === "GET") {
          http_opts.path = "" + http_opts.path + "?" + (querystringify(options));
        } else {
          query || (query = {});
          query.options = options;
        }
      }
      if (query != null) {
        query = JSON.stringify(query);
        opts.headers["Content-Type"] = "application/json";
        opts.headers["Content-Length"] = query.length;
      }
      req = this.asana.http.request(http_opts, function(res) {
        var data;
        data = "";
        res.on("data", function(buf) {
          return data += buf;
        });
        return res.on("end", function() {
          try {
            data = JSON.parse(data);
          } catch (err) {

          }
          if (res.statusCode !== expects) {
            err = {
              code: res.statusCode,
              headers: res.headers,
              options: http_opts,
              query: query,
              response: data
            };
            return error(model, err);
          }
          return success(data.data, res.statusCode, res);
        });
      });
      return req.end(query);
    };

    return Asana;

  })();

  module.exports.Asana = Asana;

}).call(this);
