// Generated by CoffeeScript 1.3.1
(function() {
  var Collection, Model, User, Users, b64, defaults, isEmpty, querystringify, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  _ref = require("./utils"), b64 = _ref.b64, defaults = _ref.defaults, querystringify = _ref.querystringify, isEmpty = _ref.isEmpty;

  _ref1 = require("backbone"), Collection = _ref1.Collection, Model = _ref1.Model;

  module.exports.Asana = (function() {

    Asana.name = 'Asana';

    function Asana(opts) {
      var addClass, self;
      this.asana = {
        params: {
          auth: b64("" + opts.key + ":"),
          path: opts.path || "/api/1.0",
          host: opts.host || "app.asana.com",
          scheme: opts.scheme || "https",
          options: opts.options || {}
        },
        read: function() {
          return {
            method: "GET",
            expects: 200
          };
        }
      };
      if (this.asana.params.scheme === "https") {
        this.asana.http = require("https");
        this.asana.params.port = opts.port || 443;
      } else {
        this.asana.http = require("http");
        this.asana.params.port = opts.port || 80;
      }
      self = this;
      addClass = function(name, klass) {
        return self[name] = (function(_super) {

          __extends(_Class, _super);

          function _Class() {
            return _Class.__super__.constructor.apply(this, arguments);
          }

          _Class.prototype.asana = self.asana;

          _Class.prototype.sync = function() {
            return self.sync.apply(this, arguments);
          };

          return _Class;

        })(klass);
      };
      addClass("User", User);
      addClass("Users", Users);
      this.Users.prototype.model = this.User;
    }

    Asana.prototype.sync = function(method, model, opts) {
      var error, expects, headers, http_opts, options, params, query, req, success, url;
      if (opts == null) {
        opts = {};
      }
      params = model.asana[method]();
      url = typeof this.url === "function" ? this.url() : this.url;
      expects = params.expects || 200;
      query = params.query;
      error = opts.error || function() {};
      success = opts.success || function() {};
      options = defaults(this.asana.params.options, opts.asana);
      headers = {
        "Accept": "application/json",
        "Authorization": "Basic " + this.asana.params.auth
      };
      http_opts = {
        host: this.asana.params.host,
        port: this.asana.params.port,
        method: params.method || "GET",
        path: "" + this.asana.params.path + url,
        headers: headers,
        scheme: this.asana.params.scheme
      };
      if (!isEmpty(options)) {
        if (http_opts.method === "GET") {
          http_opts.path = "" + http_opts.path + "?" + (querystringify(options));
        } else {
          query || (query = {});
          query.options = options;
        }
      }
      if (query != null) {
        query = JSON.stringify(query);
        opts.headers["Content-Type"] = "application/json";
        opts.headers["Content-Length"] = query.length;
      }
      req = this.asana.http.request(http_opts, function(res) {
        var data;
        data = "";
        res.on("data", function(buf) {
          return data += buf;
        });
        return res.on("end", function() {
          try {
            data = JSON.parse(data);
          } catch (err) {

          }
          if (res.statusCode !== expects) {
            err = {
              code: res.statusCode,
              headers: res.headers,
              options: http_opts,
              query: query,
              response: data
            };
            return error(model, err);
          }
          return success(data.data, res.statusCode, res);
        });
      });
      return req.end(query);
    };

    return Asana;

  })();

  User = (function(_super) {

    __extends(User, _super);

    User.name = 'User';

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.prototype.baseUrl = "/users";

    return User;

  })(Model);

  Users = (function(_super) {

    __extends(Users, _super);

    Users.name = 'Users';

    function Users() {
      return Users.__super__.constructor.apply(this, arguments);
    }

    Users.prototype.url = "/users";

    return Users;

  })(Collection);

}).call(this);
