// Generated by CoffeeScript 1.3.1
(function() {
  var attributify, clone, fold, fromByteArray, idify, ioOptions, optName, utf8ToBytes, _;

  _ = require("underscore");

  fromByteArray = require("base64-js").fromByteArray;

  utf8ToBytes = function(str) {
    var byteArray, h, i, j, _i, _j, _ref, _ref1;
    byteArray = [];
    for (i = _i = 0, _ref = str.length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (str.charCodeAt(i) <= 0x7F) {
        byteArray.push(str.charCodeAt(i));
      } else {
        h = encodeURIComponent(str.charAt(i)).substr(1).split("%");
        for (j = _j = 0, _ref1 = h.length; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
          byteArray.push(parseInt(h[j], 16));
        }
      }
    }
    return byteArray;
  };

  module.exports.b64 = function(str) {
    return fromByteArray(utf8ToBytes(str));
  };

  fold = function(src, dst, fn) {
    return _.reduce(src, fn, dst);
  };

  module.exports.clone = clone = _.clone;

  module.exports.defaults = function(defaults, src) {
    var key, res, value;
    if (src == null) {
      src = {};
    }
    res = clone(defaults);
    for (key in src) {
      value = src[key];
      res[key] = value;
    }
    return res;
  };

  module.exports.idify = idify = function(src) {
    var element;
    if (!((src != null) && typeof src === "object")) {
      return src;
    }
    if (src.id != null) {
      return src.id;
    }
    if (src instanceof Array) {
      return (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = src.length; _i < _len; _i++) {
          element = src[_i];
          _results.push(idify(element));
        }
        return _results;
      })();
    }
    return fold(src, {}, function(cur, value, key) {
      cur[key] = idify(value);
      return cur;
    });
  };

  module.exports.attributify = attributify = function(src) {
    var element;
    if (!((src != null) && typeof src === "object")) {
      return src;
    }
    if (src.attributes != null) {
      return src.attributes;
    }
    if (src instanceof Array) {
      return (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = src.length; _i < _len; _i++) {
          element = src[_i];
          _results.push(attributify(element));
        }
        return _results;
      })();
    }
    return fold(src, {}, function(cur, value, key) {
      cur[key] = attributify(value);
      return cur;
    });
  };

  module.exports.isEmpty = _.isEmpty;

  ioOptions = ["pretty", "fields", "expand"];

  optName = function(name) {
    if (ioOptions.indexOf(name) !== -1) {
      return "opt_" + name;
    } else {
      return name;
    }
  };

  module.exports.querystringify = function(arg) {
    var key, params, value;
    params = [];
    for (key in arg) {
      value = arg[key];
      key = optName(key);
      if ((value != null ? value.toString : void 0) != null) {
        params.push("" + key + "=" + (value.toString()));
      } else {
        params.push("" + key + "=" + value);
      }
    }
    return params.join("&");
  };

}).call(this);
